### ISSUE TITLE
Multyvac username and password

### ISSUE THREAD

**Issue by tanujasawant** [cloudpipe/multyvac-fork#6]
**Goal**: to setup multyvac on ubuntu 16.04
**Steps followed:**
**1)**$ pip install vac (and/or pip install multyvac)
**2)** python -m multyvac.setup
Welcome to Multyvac.

If you input your Multyvac username and password, an api key will be automatically fetched for this machine.
Username: dsefsg
Password: 
Bad username and password. Please run setup again.
(**Any username and password I type doesn't seem to work- where does one get multyvac username and password?**)
**3)** in the python terminal:

> > > import multyvac
> > > def add(x, y):
> > >    ...     return x + y
> > > add(1, 2)
> > >    3
> > > job_id = multyvac.submit(add, 1, 2)

**Gives this error:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fay/anaconda2/lib/python2.7/site-packages/multyvac/job.py", line 422, in submit
    **kwargs
  File "/home/fay/anaconda2/lib/python2.7/site-packages/multyvac/job.py", line 341, in shell_submit
    content_type_json=True)
  File "/home/fay/anaconda2/lib/python2.7/site-packages/multyvac/multyvac.py", line 233, in _ask
    files=files)
  File "/home/fay/anaconda2/lib/python2.7/site-packages/multyvac/multyvac.py", line 257, in _ask_helper
    auth = self.config.get_auth()
  File "/home/fay/anaconda2/lib/python2.7/site-packages/multyvac/config.py", line 116, in get_auth
    raise ConfigError('Api Key is not set')
multyvac.config.ConfigError: Api Key is not set

How to fix this?
Can someone please help? I didn't find any help online

**Comment by rgbkrk** [comment]
We don't support the multyvac servers whatsoever, this was put together to support the creation of an alternate version since multyvac never seemed to shine the light of day.

What are you trying to do?

**Comment by tanujasawant** [comment]
Hi! I found an alternative, I'll close the issue. Thanks a lot :)
